// Constantes compartilhadas para tipos de itens

export const ITEM_TYPES = [
  { value: 'stone_brick', label: 'Stone Brick' },
  { value: 'colossus_brick', label: 'Colossus Brick' },
  { value: 'slate_brick', label: 'Slate Brick' },
  { value: 'marble_brick', label: 'Marble Bricks' },
  { value: 'sandstone_brick', label: 'Sandstone Brick' },
  { value: 'pottery_brick', label: 'Pottery Bricks' },
  { value: 'clay', label: 'Clay' },
  { value: 'sand', label: 'Sand' },
  { value: 'dirt', label: 'Dirt' },
  { value: 'stone_shard', label: 'Stone Shards' },
  { value: 'slate_shard', label: 'Slate Shards' },
  { value: 'marble_shard', label: 'Marble Shards' },
  { value: 'sandstone_shard', label: 'Sandstone Shards' },
  { value: 'mortar', label: 'Mortar' },
  // Metals
  { value: 'iron_lump', label: 'Iron Lump' },
  { value: 'copper_lump', label: 'Copper Lump' },
  { value: 'silver_lump', label: 'Silver Lump' },
  { value: 'gold_lump', label: 'Gold Lump' },
  { value: 'tin_lump', label: 'Tin Lump' },
  { value: 'zinc_lump', label: 'Zinc Lump' },
  { value: 'lead_lump', label: 'Lead Lump' },
  { value: 'empyrean_lump', label: 'Empyrean Lump' },
  { value: 'steel_lump', label: 'Steel Lump' },
  { value: 'brass_lump', label: 'Brass Lump' },
  { value: 'bronze_lump', label: 'Bronze Lump' },
  { value: 'electrum_lump', label: 'Electrum Lump' },
  { value: 'glimmersteel_lump', label: 'Glimmersteel Lump' },
  { value: 'adamantine_lump', label: 'Adamantine Lump' },
  { value: 'seryll_lump', label: 'Seryll Lump' },
  // Ores
  { value: 'iron_ore', label: 'Iron Ore' },
  { value: 'copper_ore', label: 'Copper Ore' },
  { value: 'silver_ore', label: 'Silver Ore' },
  { value: 'gold_ore', label: 'Gold Ore' },
  { value: 'tin_ore', label: 'Tin Ore' },
  { value: 'zinc_ore', label: 'Zinc Ore' },
  { value: 'lead_ore', label: 'Lead Ore' },
  // Smithing
  { value: 'small_nail', label: 'Small Nail' },
  { value: 'large_nail', label: 'Large Nail' },
  { value: 'ribbon', label: 'Ribbon' },
  // Wood
  { value: 'apple_log', label: 'Apple Log' },
  { value: 'apple_plank', label: 'Apple Plank' },
  { value: 'apple_wooden_beam', label: 'Apple Wooden Beam' },
  { value: 'apple_shaft', label: 'Apple Shaft' },
  { value: 'apple_branch', label: 'Apple Branch' },
  { value: 'apple_peg', label: 'Apple Peg' },
  { value: 'apple_tenon', label: 'Apple Tenon' },
  { value: 'birch_log', label: 'Birch Log' },
  { value: 'birch_plank', label: 'Birch Plank' },
  { value: 'birch_wooden_beam', label: 'Birch Wooden Beam' },
  { value: 'birch_shaft', label: 'Birch Shaft' },
  { value: 'birch_branch', label: 'Birch Branch' },
  { value: 'birch_peg', label: 'Birch Peg' },
  { value: 'birch_tenon', label: 'Birch Tenon' },
  { value: 'cedar_log', label: 'Cedar Log' },
  { value: 'cedar_plank', label: 'Cedar Plank' },
  { value: 'cedar_wooden_beam', label: 'Cedar Wooden Beam' },
  { value: 'cedar_shaft', label: 'Cedar Shaft' },
  { value: 'cedar_branch', label: 'Cedar Branch' },
  { value: 'cedar_peg', label: 'Cedar Peg' },
  { value: 'cedar_tenon', label: 'Cedar Tenon' },
  { value: 'cherry_log', label: 'Cherry Log' },
  { value: 'cherry_plank', label: 'Cherry Plank' },
  { value: 'cherry_wooden_beam', label: 'Cherry Wooden Beam' },
  { value: 'cherry_shaft', label: 'Cherry Shaft' },
  { value: 'cherry_branch', label: 'Cherry Branch' },
  { value: 'cherry_peg', label: 'Cherry Peg' },
  { value: 'cherry_tenon', label: 'Cherry Tenon' },
  { value: 'chestnut_log', label: 'Chestnut Log' },
  { value: 'chestnut_plank', label: 'Chestnut Plank' },
  { value: 'chestnut_wooden_beam', label: 'Chestnut Wooden Beam' },
  { value: 'chestnut_shaft', label: 'Chestnut Shaft' },
  { value: 'chestnut_branch', label: 'Chestnut Branch' },
  { value: 'chestnut_peg', label: 'Chestnut Peg' },
  { value: 'chestnut_tenon', label: 'Chestnut Tenon' },
  { value: 'fir_log', label: 'Fir Log' },
  { value: 'fir_plank', label: 'Fir Plank' },
  { value: 'fir_wooden_beam', label: 'Fir Wooden Beam' },
  { value: 'fir_shaft', label: 'Fir Shaft' },
  { value: 'fir_branch', label: 'Fir Branch' },
  { value: 'fir_peg', label: 'Fir Peg' },
  { value: 'fir_tenon', label: 'Fir Tenon' },
  { value: 'lemon_log', label: 'Lemon Log' },
  { value: 'lemon_plank', label: 'Lemon Plank' },
  { value: 'lemon_wooden_beam', label: 'Lemon Wooden Beam' },
  { value: 'lemon_shaft', label: 'Lemon Shaft' },
  { value: 'lemon_branch', label: 'Lemon Branch' },
  { value: 'lemon_peg', label: 'Lemon Peg' },
  { value: 'lemon_tenon', label: 'Lemon Tenon' },
  { value: 'linden_log', label: 'Linden Log' },
  { value: 'linden_plank', label: 'Linden Plank' },
  { value: 'linden_wooden_beam', label: 'Linden Wooden Beam' },
  { value: 'linden_shaft', label: 'Linden Shaft' },
  { value: 'linden_branch', label: 'Linden Branch' },
  { value: 'linden_peg', label: 'Linden Peg' },
  { value: 'linden_tenon', label: 'Linden Tenon' },
  { value: 'maple_log', label: 'Maple Log' },
  { value: 'maple_plank', label: 'Maple Plank' },
  { value: 'maple_wooden_beam', label: 'Maple Wooden Beam' },
  { value: 'maple_shaft', label: 'Maple Shaft' },
  { value: 'maple_branch', label: 'Maple Branch' },
  { value: 'maple_peg', label: 'Maple Peg' },
  { value: 'maple_tenon', label: 'Maple Tenon' },
  { value: 'oak_log', label: 'Oak Log' },
  { value: 'oak_plank', label: 'Oak Plank' },
  { value: 'oak_wooden_beam', label: 'Oak Wooden Beam' },
  { value: 'oak_shaft', label: 'Oak Shaft' },
  { value: 'oak_branch', label: 'Oak Branch' },
  { value: 'oak_peg', label: 'Oak Peg' },
  { value: 'oak_tenon', label: 'Oak Tenon' },
  { value: 'oleander_log', label: 'Oleander Log' },
  { value: 'oleander_plank', label: 'Oleander Plank' },
  { value: 'oleander_wooden_beam', label: 'Oleander Wooden Beam' },
  { value: 'oleander_shaft', label: 'Oleander Shaft' },
  { value: 'oleander_branch', label: 'Oleander Branch' },
  { value: 'oleander_peg', label: 'Oleander Peg' },
  { value: 'oleander_tenon', label: 'Oleander Tenon' },
  { value: 'olive_log', label: 'Olive Log' },
  { value: 'olive_plank', label: 'Olive Plank' },
  { value: 'olive_wooden_beam', label: 'Olive Wooden Beam' },
  { value: 'olive_shaft', label: 'Olive Shaft' },
  { value: 'olive_branch', label: 'Olive Branch' },
  { value: 'olive_peg', label: 'Olive Peg' },
  { value: 'olive_tenon', label: 'Olive Tenon' },
  { value: 'orange_log', label: 'Orange Log' },
  { value: 'orange_plank', label: 'Orange Plank' },
  { value: 'orange_wooden_beam', label: 'Orange Wooden Beam' },
  { value: 'orange_shaft', label: 'Orange Shaft' },
  { value: 'orange_branch', label: 'Orange Branch' },
  { value: 'orange_peg', label: 'Orange Peg' },
  { value: 'orange_tenon', label: 'Orange Tenon' },
  { value: 'pine_log', label: 'Pine Log' },
  { value: 'pine_plank', label: 'Pine Plank' },
  { value: 'pine_wooden_beam', label: 'Pine Wooden Beam' },
  { value: 'pine_shaft', label: 'Pine Shaft' },
  { value: 'pine_branch', label: 'Pine Branch' },
  { value: 'pine_peg', label: 'Pine Peg' },
  { value: 'pine_tenon', label: 'Pine Tenon' },
  { value: 'walnut_log', label: 'Walnut Log' },
  { value: 'walnut_plank', label: 'Walnut Plank' },
  { value: 'walnut_wooden_beam', label: 'Walnut Wooden Beam' },
  { value: 'walnut_shaft', label: 'Walnut Shaft' },
  { value: 'walnut_branch', label: 'Walnut Branch' },
  { value: 'walnut_peg', label: 'Walnut Peg' },
  { value: 'walnut_tenon', label: 'Walnut Tenon' },
  { value: 'willow_log', label: 'Willow Log' },
  { value: 'willow_plank', label: 'Willow Plank' },
  { value: 'willow_wooden_beam', label: 'Willow Wooden Beam' },
  { value: 'willow_shaft', label: 'Willow Shaft' },
  { value: 'willow_branch', label: 'Willow Branch' },
  { value: 'willow_peg', label: 'Willow Peg' },
  { value: 'willow_tenon', label: 'Willow Tenon' },
  { value: 'blueberry_log', label: 'Blueberry Log' },
  { value: 'blueberry_plank', label: 'Blueberry Plank' },
  { value: 'blueberry_wooden_beam', label: 'Blueberry Wooden Beam' },
  { value: 'blueberry_shaft', label: 'Blueberry Shaft' },
  { value: 'blueberry_branch', label: 'Blueberry Branch' },
  { value: 'blueberry_peg', label: 'Blueberry Peg' },
  { value: 'blueberry_tenon', label: 'Blueberry Tenon' },
  { value: 'raspberry_log', label: 'Raspberry Log' },
  { value: 'raspberry_plank', label: 'Raspberry Plank' },
  { value: 'raspberry_wooden_beam', label: 'Raspberry Wooden Beam' },
  { value: 'raspberry_shaft', label: 'Raspberry Shaft' },
  { value: 'raspberry_branch', label: 'Raspberry Branch' },
  { value: 'raspberry_peg', label: 'Raspberry Peg' },
  { value: 'raspberry_tenon', label: 'Raspberry Tenon' },
  { value: 'grape_log', label: 'Grape Log' },
  { value: 'grape_plank', label: 'Grape Plank' },
  { value: 'grape_wooden_beam', label: 'Grape Wooden Beam' },
  { value: 'grape_shaft', label: 'Grape Shaft' },
  { value: 'grape_branch', label: 'Grape Branch' },
  { value: 'grape_peg', label: 'Grape Peg' },
  { value: 'grape_tenon', label: 'Grape Tenon' },
  { value: 'hazelnut_log', label: 'Hazelnut Log' },
  { value: 'hazelnut_plank', label: 'Hazelnut Plank' },
  { value: 'hazelnut_wooden_beam', label: 'Hazelnut Wooden Beam' },
  { value: 'hazelnut_shaft', label: 'Hazelnut Shaft' },
  { value: 'hazelnut_branch', label: 'Hazelnut Branch' },
  { value: 'hazelnut_peg', label: 'Hazelnut Peg' },
  { value: 'hazelnut_tenon', label: 'Hazelnut Tenon' },
  { value: 'thorn_log', label: 'Thorn Log' },
  { value: 'thorn_plank', label: 'Thorn Plank' },
  { value: 'thorn_wooden_beam', label: 'Thorn Wooden Beam' },
  { value: 'thorn_shaft', label: 'Thorn Shaft' },
  { value: 'thorn_branch', label: 'Thorn Branch' },
  { value: 'thorn_peg', label: 'Thorn Peg' },
  { value: 'thorn_tenon', label: 'Thorn Tenon' },
  { value: 'lavender_log', label: 'Lavender Log' },
  { value: 'lavender_plank', label: 'Lavender Plank' },
  { value: 'lavender_wooden_beam', label: 'Lavender Wooden Beam' },
  { value: 'lavender_shaft', label: 'Lavender Shaft' },
  { value: 'lavender_branch', label: 'Lavender Branch' },
  { value: 'lavender_peg', label: 'Lavender Peg' },
  { value: 'lavender_tenon', label: 'Lavender Tenon' },
  { value: 'camelia_log', label: 'Camelia Log' },
  { value: 'camelia_plank', label: 'Camelia Plank' },
  { value: 'camelia_wooden_beam', label: 'Camelia Wooden Beam' },
  { value: 'camelia_shaft', label: 'Camelia Shaft' },
  { value: 'camelia_branch', label: 'Camelia Branch' },
  { value: 'camelia_peg', label: 'Camelia Peg' },
  { value: 'camelia_tenon', label: 'Camelia Tenon' },
  { value: 'rose_log', label: 'Rose Log' },
  { value: 'rose_plank', label: 'Rose Plank' },
  { value: 'rose_wooden_beam', label: 'Rose Wooden Beam' },
  { value: 'rose_shaft', label: 'Rose Shaft' },
  { value: 'rose_branch', label: 'Rose Branch' },
  { value: 'rose_peg', label: 'Rose Peg' },
  { value: 'rose_tenon', label: 'Rose Tenon' },
  { value: 'lingoberry_log', label: 'Lingoberry Log' },
  { value: 'lingoberry_plank', label: 'Lingoberry Plank' },
  { value: 'lingoberry_wooden_beam', label: 'Lingoberry Wooden Beam' },
  { value: 'lingoberry_shaft', label: 'Lingoberry Shaft' },
  { value: 'lingoberry_branch', label: 'Lingoberry Branch' },
  { value: 'lingoberry_peg', label: 'Lingoberry Peg' },
  { value: 'lingoberry_tenon', label: 'Lingoberry Tenon' },
  // Farm
  { value: 'potato', label: 'Potato' },
  { value: 'cotton', label: 'Cotton' },
  { value: 'rye', label: 'Rye' },
  { value: 'wemp', label: 'Wemp' },
  { value: 'cucumber', label: 'Cucumber' },
  { value: 'oat', label: 'Oat' },
  { value: 'pumpkin', label: 'Pumpkin' },
  { value: 'barley', label: 'Barley' },
  { value: 'reed', label: 'Reed' },
  { value: 'carrot', label: 'Carrot' },
  { value: 'hay', label: 'Hay' },
  { value: 'wheat', label: 'Wheat' },
  { value: 'cabbage', label: 'Cabbage' },
  { value: 'corn', label: 'Corn' },
  { value: 'tomato', label: 'Tomato' },
  { value: 'lettuce', label: 'Lettuce' },
  { value: 'onion', label: 'Onion' },
  { value: 'strawberries', label: 'Strawberries' },
  { value: 'pea_pod', label: 'Pea Pod' },
  { value: 'garlic', label: 'Garlic' },
  { value: 'rice', label: 'Rice' },
  { value: 'sugar_beet', label: 'Sugar Beet' },
  { value: 'black_mushroom', label: 'Black Mushroom' },
  { value: 'green_mushroom', label: 'Green Mushroom' },
  { value: 'yellow_mushroom', label: 'Yellow Mushroom' },
  { value: 'blue_mushroom', label: 'Blue Mushroom' },
  { value: 'brown_mushroom', label: 'Brown Mushroom' },
  { value: 'red_mushroom', label: 'Red Mushroom' },
  // Garden
  { value: 'basil', label: 'Basil' },
  { value: 'belladonna', label: 'Belladonna' },
  { value: 'fennel', label: 'Fennel' },
  { value: 'lovage', label: 'Lovage' },
  { value: 'mint', label: 'Mint' },
  { value: 'oregano', label: 'Oregano' },
  { value: 'parsley', label: 'Parsley' },
  { value: 'rosemary', label: 'Rosemary' },
  { value: 'sage', label: 'Sage' },
  { value: 'thyme', label: 'Thyme' },
  { value: 'cumin', label: 'Cumin' },
  { value: 'ginger', label: 'Ginger' },
  { value: 'paprika', label: 'Paprika' },
  { value: 'turmeric', label: 'Turmeric' },
  { value: 'woad', label: 'Woad' },
  { value: 'green_coffee_beans', label: 'Green Coffee Beans' },
  { value: 'tea_seeds', label: 'Tea Seeds' },
  { value: 'cacao_beans', label: 'Cacao Beans' },
  // Animal
  { value: 'fat', label: 'Fat' },
  { value: 'hide', label: 'Hide' },
  { value: 'bladder', label: 'Bladder' },
  { value: 'cochineal', label: 'Cochineal' },
  { value: 'crab_meat', label: 'Crab Meat' },
  { value: 'dragon_scale', label: 'Dragon Scale' },
  { value: 'drake_hide', label: 'Drake Hide' },
  { value: 'eye', label: 'Eye' },
  { value: 'feather', label: 'Feather' },
  { value: 'fish_fillet', label: 'Fish Fillet' },
  { value: 'flint', label: 'Flint' },
  { value: 'fur', label: 'Fur' },
  { value: 'gland', label: 'Gland' },
  { value: 'goblin_skull', label: 'Goblin Skull' },
  { value: 'heart', label: 'Heart' },
  { value: 'hoof', label: 'Hoof' },
  { value: 'horn', label: 'Horn' },
  { value: 'long_horn', label: 'Long Horn' },
  { value: 'bear_meat', label: 'Bear Meat' },
  { value: 'beef_meat', label: 'Beef Meat' },
  { value: 'canine_meat', label: 'Canine Meat' },
  { value: 'dragon_meat', label: 'Dragon Meat' },
  { value: 'feline_meat', label: 'Feline Meat' },
  { value: 'fowl_meat', label: 'Fowl Meat' },
  { value: 'game_meat', label: 'Game Meat' },
  { value: 'horse_meat', label: 'Horse Meat' },
  { value: 'human_meat', label: 'Human Meat' },
  { value: 'humanoid_meat', label: 'Humanoid Meat' },
  { value: 'insect_meat', label: 'Insect Meat' },
  { value: 'lamb_meat', label: 'Lamb Meat' },
  { value: 'pork_meat', label: 'Pork Meat' },
  { value: 'seafood_meat', label: 'Seafood Meat' },
  { value: 'snake_meat', label: 'Snake Meat' },
  { value: 'toughat_meat', label: 'Toughat Meat' },
  { value: 'octopus_ink_sac', label: 'Octopus Ink Sac' },
  { value: 'paw', label: 'Paw' },
  { value: 'pelt', label: 'Pelt' },
  { value: 'skull', label: 'Skull' },
  { value: 'small_tortoise_shell', label: 'Small Tortoise Shell' },
  { value: 'tail', label: 'Tail' },
  { value: 'tooth', label: 'Tooth' },
  { value: 'unicorn_twisted_horn', label: 'Unicorn Twisted Horn' },
  { value: 'wool', label: 'Wool' },
  // Fruits
  { value: 'apples', label: 'Apples' },
  { value: 'cherries', label: 'Cherries' },
  { value: 'blue_grapes', label: 'Blue Grapes' },
  { value: 'green_grapes', label: 'Green Grapes' },
  { value: 'lemons', label: 'Lemons' },
  { value: 'olives', label: 'Olives' },
  { value: 'oranges', label: 'Oranges' },
  { value: 'blueberries', label: 'Blueberries' },
  { value: 'lingonberries', label: 'Lingonberries' },
  { value: 'raspberries', label: 'Raspberries' },
  { value: 'acorns', label: 'Acorns' },
  { value: 'chestnuts', label: 'Chestnuts' },
  { value: 'hazelnuts', label: 'Hazelnuts' },
  { value: 'pinenuts', label: 'Pinenuts' },
  { value: 'walnuts', label: 'Walnuts' },
]

export const ITEM_TYPE_LABELS = { 
  stone_brick: 'Stone Brick',
  colossus_brick: 'Colossus Brick',
  slate_brick: 'Slate Brick',
  marble_brick: 'Marble Bricks',
  sandstone_brick: 'Sandstone Brick',
  pottery_brick: 'Pottery Bricks',
  clay: 'Clay',
  sand: 'Sand',
  dirt: 'Dirt',
  stone_shard: 'Stone Shards',
  slate_shard: 'Slate Shards',
  marble_shard: 'Marble Shards',
  sandstone_shard: 'Sandstone Shards',
  mortar: 'Mortar',
  // Metals
  iron_lump: 'Iron Lump',
  copper_lump: 'Copper Lump',
  silver_lump: 'Silver Lump',
  gold_lump: 'Gold Lump',
  tin_lump: 'Tin Lump',
  zinc_lump: 'Zinc Lump',
  lead_lump: 'Lead Lump',
  empyrean_lump: 'Empyrean Lump',
  steel_lump: 'Steel Lump',
  brass_lump: 'Brass Lump',
  bronze_lump: 'Bronze Lump',
  electrum_lump: 'Electrum Lump',
  glimmersteel_lump: 'Glimmersteel Lump',
  adamantine_lump: 'Adamantine Lump',
  seryll_lump: 'Seryll Lump',
  // Ores
  iron_ore: 'Iron Ore',
  copper_ore: 'Copper Ore',
  silver_ore: 'Silver Ore',
  gold_ore: 'Gold Ore',
  tin_ore: 'Tin Ore',
  zinc_ore: 'Zinc Ore',
  lead_ore: 'Lead Ore',
  // Smithing
  small_nail: 'Small Nail',
  large_nail: 'Large Nail',
  ribbon: 'Ribbon',
  // Wood
  apple_log: 'Apple Log',
  apple_plank: 'Apple Plank',
  apple_wooden_beam: 'Apple Wooden Beam',
  apple_shaft: 'Apple Shaft',
  apple_branch: 'Apple Branch',
  apple_peg: 'Apple Peg',
  apple_tenon: 'Apple Tenon',
  birch_log: 'Birch Log',
  birch_plank: 'Birch Plank',
  birch_wooden_beam: 'Birch Wooden Beam',
  birch_shaft: 'Birch Shaft',
  birch_branch: 'Birch Branch',
  birch_peg: 'Birch Peg',
  birch_tenon: 'Birch Tenon',
  cedar_log: 'Cedar Log',
  cedar_plank: 'Cedar Plank',
  cedar_wooden_beam: 'Cedar Wooden Beam',
  cedar_shaft: 'Cedar Shaft',
  cedar_branch: 'Cedar Branch',
  cedar_peg: 'Cedar Peg',
  cedar_tenon: 'Cedar Tenon',
  cherry_log: 'Cherry Log',
  cherry_plank: 'Cherry Plank',
  cherry_wooden_beam: 'Cherry Wooden Beam',
  cherry_shaft: 'Cherry Shaft',
  cherry_branch: 'Cherry Branch',
  cherry_peg: 'Cherry Peg',
  cherry_tenon: 'Cherry Tenon',
  chestnut_log: 'Chestnut Log',
  chestnut_plank: 'Chestnut Plank',
  chestnut_wooden_beam: 'Chestnut Wooden Beam',
  chestnut_shaft: 'Chestnut Shaft',
  chestnut_branch: 'Chestnut Branch',
  chestnut_peg: 'Chestnut Peg',
  chestnut_tenon: 'Chestnut Tenon',
  fir_log: 'Fir Log',
  fir_plank: 'Fir Plank',
  fir_wooden_beam: 'Fir Wooden Beam',
  fir_shaft: 'Fir Shaft',
  fir_branch: 'Fir Branch',
  fir_peg: 'Fir Peg',
  fir_tenon: 'Fir Tenon',
  lemon_log: 'Lemon Log',
  lemon_plank: 'Lemon Plank',
  lemon_wooden_beam: 'Lemon Wooden Beam',
  lemon_shaft: 'Lemon Shaft',
  lemon_branch: 'Lemon Branch',
  lemon_peg: 'Lemon Peg',
  lemon_tenon: 'Lemon Tenon',
  linden_log: 'Linden Log',
  linden_plank: 'Linden Plank',
  linden_wooden_beam: 'Linden Wooden Beam',
  linden_shaft: 'Linden Shaft',
  linden_branch: 'Linden Branch',
  linden_peg: 'Linden Peg',
  linden_tenon: 'Linden Tenon',
  maple_log: 'Maple Log',
  maple_plank: 'Maple Plank',
  maple_wooden_beam: 'Maple Wooden Beam',
  maple_shaft: 'Maple Shaft',
  maple_branch: 'Maple Branch',
  maple_peg: 'Maple Peg',
  maple_tenon: 'Maple Tenon',
  oak_log: 'Oak Log',
  oak_plank: 'Oak Plank',
  oak_wooden_beam: 'Oak Wooden Beam',
  oak_shaft: 'Oak Shaft',
  oak_branch: 'Oak Branch',
  oak_peg: 'Oak Peg',
  oak_tenon: 'Oak Tenon',
  oleander_log: 'Oleander Log',
  oleander_plank: 'Oleander Plank',
  oleander_wooden_beam: 'Oleander Wooden Beam',
  oleander_shaft: 'Oleander Shaft',
  oleander_branch: 'Oleander Branch',
  oleander_peg: 'Oleander Peg',
  oleander_tenon: 'Oleander Tenon',
  olive_log: 'Olive Log',
  olive_plank: 'Olive Plank',
  olive_wooden_beam: 'Olive Wooden Beam',
  olive_shaft: 'Olive Shaft',
  olive_branch: 'Olive Branch',
  olive_peg: 'Olive Peg',
  olive_tenon: 'Olive Tenon',
  orange_log: 'Orange Log',
  orange_plank: 'Orange Plank',
  orange_wooden_beam: 'Orange Wooden Beam',
  orange_shaft: 'Orange Shaft',
  orange_branch: 'Orange Branch',
  orange_peg: 'Orange Peg',
  orange_tenon: 'Orange Tenon',
  pine_log: 'Pine Log',
  pine_plank: 'Pine Plank',
  pine_wooden_beam: 'Pine Wooden Beam',
  pine_shaft: 'Pine Shaft',
  pine_branch: 'Pine Branch',
  pine_peg: 'Pine Peg',
  pine_tenon: 'Pine Tenon',
  walnut_log: 'Walnut Log',
  walnut_plank: 'Walnut Plank',
  walnut_wooden_beam: 'Walnut Wooden Beam',
  walnut_shaft: 'Walnut Shaft',
  walnut_branch: 'Walnut Branch',
  walnut_peg: 'Walnut Peg',
  walnut_tenon: 'Walnut Tenon',
  willow_log: 'Willow Log',
  willow_plank: 'Willow Plank',
  willow_wooden_beam: 'Willow Wooden Beam',
  willow_shaft: 'Willow Shaft',
  willow_branch: 'Willow Branch',
  willow_peg: 'Willow Peg',
  willow_tenon: 'Willow Tenon',
  blueberry_log: 'Blueberry Log',
  blueberry_plank: 'Blueberry Plank',
  blueberry_wooden_beam: 'Blueberry Wooden Beam',
  blueberry_shaft: 'Blueberry Shaft',
  blueberry_branch: 'Blueberry Branch',
  blueberry_peg: 'Blueberry Peg',
  blueberry_tenon: 'Blueberry Tenon',
  raspberry_log: 'Raspberry Log',
  raspberry_plank: 'Raspberry Plank',
  raspberry_wooden_beam: 'Raspberry Wooden Beam',
  raspberry_shaft: 'Raspberry Shaft',
  raspberry_branch: 'Raspberry Branch',
  raspberry_peg: 'Raspberry Peg',
  raspberry_tenon: 'Raspberry Tenon',
  grape_log: 'Grape Log',
  grape_plank: 'Grape Plank',
  grape_wooden_beam: 'Grape Wooden Beam',
  grape_shaft: 'Grape Shaft',
  grape_branch: 'Grape Branch',
  grape_peg: 'Grape Peg',
  grape_tenon: 'Grape Tenon',
  hazelnut_log: 'Hazelnut Log',
  hazelnut_plank: 'Hazelnut Plank',
  hazelnut_wooden_beam: 'Hazelnut Wooden Beam',
  hazelnut_shaft: 'Hazelnut Shaft',
  hazelnut_branch: 'Hazelnut Branch',
  hazelnut_peg: 'Hazelnut Peg',
  hazelnut_tenon: 'Hazelnut Tenon',
  thorn_log: 'Thorn Log',
  thorn_plank: 'Thorn Plank',
  thorn_wooden_beam: 'Thorn Wooden Beam',
  thorn_shaft: 'Thorn Shaft',
  thorn_branch: 'Thorn Branch',
  thorn_peg: 'Thorn Peg',
  thorn_tenon: 'Thorn Tenon',
  lavender_log: 'Lavender Log',
  lavender_plank: 'Lavender Plank',
  lavender_wooden_beam: 'Lavender Wooden Beam',
  lavender_shaft: 'Lavender Shaft',
  lavender_branch: 'Lavender Branch',
  lavender_peg: 'Lavender Peg',
  lavender_tenon: 'Lavender Tenon',
  camelia_log: 'Camelia Log',
  camelia_plank: 'Camelia Plank',
  camelia_wooden_beam: 'Camelia Wooden Beam',
  camelia_shaft: 'Camelia Shaft',
  camelia_branch: 'Camelia Branch',
  camelia_peg: 'Camelia Peg',
  camelia_tenon: 'Camelia Tenon',
  rose_log: 'Rose Log',
  rose_plank: 'Rose Plank',
  rose_wooden_beam: 'Rose Wooden Beam',
  rose_shaft: 'Rose Shaft',
  rose_branch: 'Rose Branch',
  rose_peg: 'Rose Peg',
  rose_tenon: 'Rose Tenon',
  lingoberry_log: 'Lingoberry Log',
  lingoberry_plank: 'Lingoberry Plank',
  lingoberry_wooden_beam: 'Lingoberry Wooden Beam',
  lingoberry_shaft: 'Lingoberry Shaft',
  lingoberry_branch: 'Lingoberry Branch',
  lingoberry_peg: 'Lingoberry Peg',
  lingoberry_tenon: 'Lingoberry Tenon',
  // Farm
  potato: 'Potato',
  cotton: 'Cotton',
  rye: 'Rye',
  wemp: 'Wemp',
  cucumber: 'Cucumber',
  oat: 'Oat',
  pumpkin: 'Pumpkin',
  barley: 'Barley',
  reed: 'Reed',
  carrot: 'Carrot',
  hay: 'Hay',
  wheat: 'Wheat',
  cabbage: 'Cabbage',
  corn: 'Corn',
  tomato: 'Tomato',
  lettuce: 'Lettuce',
  onion: 'Onion',
  pea_pod: 'Pea Pod',
  garlic: 'Garlic',
  rice: 'Rice',
  sugar_beet: 'Sugar Beet',
  black_mushroom: 'Black Mushroom',
  green_mushroom: 'Green Mushroom',
  yellow_mushroom: 'Yellow Mushroom',
  blue_mushroom: 'Blue Mushroom',
  brown_mushroom: 'Brown Mushroom',
  red_mushroom: 'Red Mushroom',
  // Garden
  basil: 'Basil',
  belladonna: 'Belladonna',
  fennel: 'Fennel',
  lovage: 'Lovage',
  mint: 'Mint',
  oregano: 'Oregano',
  parsley: 'Parsley',
  rosemary: 'Rosemary',
  sage: 'Sage',
  thyme: 'Thyme',
  cumin: 'Cumin',
  ginger: 'Ginger',
  paprika: 'Paprika',
  turmeric: 'Turmeric',
  woad: 'Woad',
  green_coffee_beans: 'Green Coffee Beans',
  tea_seeds: 'Tea Seeds',
  cacao_beans: 'Cacao Beans',
  // Animal
  fat: 'Fat',
  hide: 'Hide',
  bladder: 'Bladder',
  cochineal: 'Cochineal',
  crab_meat: 'Crab Meat',
  dragon_scale: 'Dragon Scale',
  drake_hide: 'Drake Hide',
  eye: 'Eye',
  feather: 'Feather',
  fish_fillet: 'Fish Fillet',
  flint: 'Flint',
  fur: 'Fur',
  gland: 'Gland',
  goblin_skull: 'Goblin Skull',
  heart: 'Heart',
  hoof: 'Hoof',
  horn: 'Horn',
  long_horn: 'Long Horn',
  bear_meat: 'Bear Meat',
  beef_meat: 'Beef Meat',
  canine_meat: 'Canine Meat',
  dragon_meat: 'Dragon Meat',
  feline_meat: 'Feline Meat',
  fowl_meat: 'Fowl Meat',
  game_meat: 'Game Meat',
  horse_meat: 'Horse Meat',
  human_meat: 'Human Meat',
  humanoid_meat: 'Humanoid Meat',
  insect_meat: 'Insect Meat',
  lamb_meat: 'Lamb Meat',
  pork_meat: 'Pork Meat',
  seafood_meat: 'Seafood Meat',
  snake_meat: 'Snake Meat',
  toughat_meat: 'Toughat Meat',
  octopus_ink_sac: 'Octopus Ink Sac',
  paw: 'Paw',
  pelt: 'Pelt',
  skull: 'Skull',
  small_tortoise_shell: 'Small Tortoise Shell',
  tail: 'Tail',
  tooth: 'Tooth',
  unicorn_twisted_horn: 'Unicorn Twisted Horn',
  wool: 'Wool',
  // Fruits
  apples: 'Apples',
  cherries: 'Cherries',
  blue_grapes: 'Blue Grapes',
  green_grapes: 'Green Grapes',
  lemons: 'Lemons',
  olives: 'Olives',
  oranges: 'Oranges',
  blueberries: 'Blueberries',
  lingonberries: 'Lingonberries',
  strawberries: 'Strawberries',
  raspberries: 'Raspberries',
  acorns: 'Acorns',
  chestnuts: 'Chestnuts',
  hazelnuts: 'Hazelnuts',
  pinenuts: 'Pinenuts',
  walnuts: 'Walnuts',
}

// Mapeamento de categorias para cada tipo de item
export const ITEM_CATEGORIES = {
  stone_shard: 'Shards',
  slate_shard: 'Shards',
  marble_shard: 'Shards',
  sandstone_shard: 'Shards',
  stone_brick: 'Bricks',
  colossus_brick: 'Bricks',
  pottery_brick: 'Bricks',
  slate_brick: 'Bricks',
  marble_brick: 'Bricks',
  sandstone_brick: 'Bricks',
  clay: 'Construction',
  sand: 'Construction',
  dirt: 'Construction',
  mortar: 'Construction',
  // Metals
  iron_lump: 'Metals',
  copper_lump: 'Metals',
  silver_lump: 'Metals',
  gold_lump: 'Metals',
  tin_lump: 'Metals',
  zinc_lump: 'Metals',
  lead_lump: 'Metals',
  empyrean_lump: 'Metals',
  steel_lump: 'Metals',
  brass_lump: 'Metals',
  bronze_lump: 'Metals',
  electrum_lump: 'Metals',
  glimmersteel_lump: 'Metals',
  adamantine_lump: 'Metals',
  seryll_lump: 'Metals',
  // Ores
  iron_ore: 'Ores',
  copper_ore: 'Ores',
  silver_ore: 'Ores',
  gold_ore: 'Ores',
  tin_ore: 'Ores',
  zinc_ore: 'Ores',
  lead_ore: 'Ores',
  // Smithing
  small_nail: 'Smithing',
  large_nail: 'Smithing',
  ribbon: 'Smithing',
  // Wood
  apple_log: 'Wood',
  apple_plank: 'Wood',
  apple_wooden_beam: 'Wood',
  apple_shaft: 'Wood',
  apple_branch: 'Wood',
  apple_peg: 'Wood',
  apple_tenon: 'Wood',
  birch_log: 'Wood',
  birch_plank: 'Wood',
  birch_wooden_beam: 'Wood',
  birch_shaft: 'Wood',
  birch_branch: 'Wood',
  birch_peg: 'Wood',
  birch_tenon: 'Wood',
  cedar_log: 'Wood',
  cedar_plank: 'Wood',
  cedar_wooden_beam: 'Wood',
  cedar_shaft: 'Wood',
  cedar_branch: 'Wood',
  cedar_peg: 'Wood',
  cedar_tenon: 'Wood',
  cherry_log: 'Wood',
  cherry_plank: 'Wood',
  cherry_wooden_beam: 'Wood',
  cherry_shaft: 'Wood',
  cherry_branch: 'Wood',
  cherry_peg: 'Wood',
  cherry_tenon: 'Wood',
  chestnut_log: 'Wood',
  chestnut_plank: 'Wood',
  chestnut_wooden_beam: 'Wood',
  chestnut_shaft: 'Wood',
  chestnut_branch: 'Wood',
  chestnut_peg: 'Wood',
  chestnut_tenon: 'Wood',
  fir_log: 'Wood',
  fir_plank: 'Wood',
  fir_wooden_beam: 'Wood',
  fir_shaft: 'Wood',
  fir_branch: 'Wood',
  fir_peg: 'Wood',
  fir_tenon: 'Wood',
  lemon_log: 'Wood',
  lemon_plank: 'Wood',
  lemon_wooden_beam: 'Wood',
  lemon_shaft: 'Wood',
  lemon_branch: 'Wood',
  lemon_peg: 'Wood',
  lemon_tenon: 'Wood',
  linden_log: 'Wood',
  linden_plank: 'Wood',
  linden_wooden_beam: 'Wood',
  linden_shaft: 'Wood',
  linden_branch: 'Wood',
  linden_peg: 'Wood',
  linden_tenon: 'Wood',
  maple_log: 'Wood',
  maple_plank: 'Wood',
  maple_wooden_beam: 'Wood',
  maple_shaft: 'Wood',
  maple_branch: 'Wood',
  maple_peg: 'Wood',
  maple_tenon: 'Wood',
  oak_log: 'Wood',
  oak_plank: 'Wood',
  oak_wooden_beam: 'Wood',
  oak_shaft: 'Wood',
  oak_branch: 'Wood',
  oak_peg: 'Wood',
  oak_tenon: 'Wood',
  oleander_log: 'Wood',
  oleander_plank: 'Wood',
  oleander_wooden_beam: 'Wood',
  oleander_shaft: 'Wood',
  oleander_branch: 'Wood',
  oleander_peg: 'Wood',
  oleander_tenon: 'Wood',
  olive_log: 'Wood',
  olive_plank: 'Wood',
  olive_wooden_beam: 'Wood',
  olive_shaft: 'Wood',
  olive_branch: 'Wood',
  olive_peg: 'Wood',
  olive_tenon: 'Wood',
  orange_log: 'Wood',
  orange_plank: 'Wood',
  orange_wooden_beam: 'Wood',
  orange_shaft: 'Wood',
  orange_branch: 'Wood',
  orange_peg: 'Wood',
  orange_tenon: 'Wood',
  pine_log: 'Wood',
  pine_plank: 'Wood',
  pine_wooden_beam: 'Wood',
  pine_shaft: 'Wood',
  pine_branch: 'Wood',
  pine_peg: 'Wood',
  pine_tenon: 'Wood',
  walnut_log: 'Wood',
  walnut_plank: 'Wood',
  walnut_wooden_beam: 'Wood',
  walnut_shaft: 'Wood',
  walnut_branch: 'Wood',
  walnut_peg: 'Wood',
  walnut_tenon: 'Wood',
  willow_log: 'Wood',
  willow_plank: 'Wood',
  willow_wooden_beam: 'Wood',
  willow_shaft: 'Wood',
  willow_branch: 'Wood',
  willow_peg: 'Wood',
  willow_tenon: 'Wood',
  blueberry_log: 'Wood',
  blueberry_plank: 'Wood',
  blueberry_wooden_beam: 'Wood',
  blueberry_shaft: 'Wood',
  blueberry_branch: 'Wood',
  blueberry_peg: 'Wood',
  blueberry_tenon: 'Wood',
  raspberry_log: 'Wood',
  raspberry_plank: 'Wood',
  raspberry_wooden_beam: 'Wood',
  raspberry_shaft: 'Wood',
  raspberry_branch: 'Wood',
  raspberry_peg: 'Wood',
  raspberry_tenon: 'Wood',
  grape_log: 'Wood',
  grape_plank: 'Wood',
  grape_wooden_beam: 'Wood',
  grape_shaft: 'Wood',
  grape_branch: 'Wood',
  grape_peg: 'Wood',
  grape_tenon: 'Wood',
  hazelnut_log: 'Wood',
  hazelnut_plank: 'Wood',
  hazelnut_wooden_beam: 'Wood',
  hazelnut_shaft: 'Wood',
  hazelnut_branch: 'Wood',
  hazelnut_peg: 'Wood',
  hazelnut_tenon: 'Wood',
  thorn_log: 'Wood',
  thorn_plank: 'Wood',
  thorn_wooden_beam: 'Wood',
  thorn_shaft: 'Wood',
  thorn_branch: 'Wood',
  thorn_peg: 'Wood',
  thorn_tenon: 'Wood',
  lavender_log: 'Wood',
  lavender_plank: 'Wood',
  lavender_wooden_beam: 'Wood',
  lavender_shaft: 'Wood',
  lavender_branch: 'Wood',
  lavender_peg: 'Wood',
  lavender_tenon: 'Wood',
  camelia_log: 'Wood',
  camelia_plank: 'Wood',
  camelia_wooden_beam: 'Wood',
  camelia_shaft: 'Wood',
  camelia_branch: 'Wood',
  camelia_peg: 'Wood',
  camelia_tenon: 'Wood',
  rose_log: 'Wood',
  rose_plank: 'Wood',
  rose_wooden_beam: 'Wood',
  rose_shaft: 'Wood',
  rose_branch: 'Wood',
  rose_peg: 'Wood',
  rose_tenon: 'Wood',
  lingoberry_log: 'Wood',
  lingoberry_plank: 'Wood',
  lingoberry_wooden_beam: 'Wood',
  lingoberry_shaft: 'Wood',
  lingoberry_branch: 'Wood',
  lingoberry_peg: 'Wood',
  lingoberry_tenon: 'Wood',
  // Farm
  potato: 'Farm',
  cotton: 'Farm',
  rye: 'Farm',
  wemp: 'Farm',
  cucumber: 'Farm',
  oat: 'Farm',
  pumpkin: 'Farm',
  barley: 'Farm',
  reed: 'Farm',
  carrot: 'Farm',
  hay: 'Farm',
  wheat: 'Farm',
  cabbage: 'Farm',
  corn: 'Farm',
  tomato: 'Farm',
  lettuce: 'Farm',
  onion: 'Farm',
  strawberries: 'Farm',
  pea_pod: 'Farm',
  garlic: 'Farm',
  rice: 'Farm',
  sugar_beet: 'Farm',
  black_mushroom: 'Farm',
  green_mushroom: 'Farm',
  yellow_mushroom: 'Farm',
  blue_mushroom: 'Farm',
  brown_mushroom: 'Farm',
  red_mushroom: 'Farm',
  // Garden
  basil: 'Garden',
  belladonna: 'Garden',
  fennel: 'Garden',
  lovage: 'Garden',
  mint: 'Garden',
  oregano: 'Garden',
  parsley: 'Garden',
  rosemary: 'Garden',
  sage: 'Garden',
  thyme: 'Garden',
  cumin: 'Garden',
  ginger: 'Garden',
  paprika: 'Garden',
  turmeric: 'Garden',
  woad: 'Garden',
  green_coffee_beans: 'Garden',
  tea_seeds: 'Garden',
  cacao_beans: 'Garden',
  // Animal
  fat: 'Animal',
  hide: 'Animal',
  bladder: 'Animal',
  cochineal: 'Animal',
  crab_meat: 'Animal',
  dragon_scale: 'Animal',
  drake_hide: 'Animal',
  eye: 'Animal',
  feather: 'Animal',
  fish_fillet: 'Animal',
  flint: 'Animal',
  fur: 'Animal',
  gland: 'Animal',
  goblin_skull: 'Animal',
  heart: 'Animal',
  hoof: 'Animal',
  horn: 'Animal',
  long_horn: 'Animal',
  bear_meat: 'Animal',
  beef_meat: 'Animal',
  canine_meat: 'Animal',
  dragon_meat: 'Animal',
  feline_meat: 'Animal',
  fowl_meat: 'Animal',
  game_meat: 'Animal',
  horse_meat: 'Animal',
  human_meat: 'Animal',
  humanoid_meat: 'Animal',
  insect_meat: 'Animal',
  lamb_meat: 'Animal',
  pork_meat: 'Animal',
  seafood_meat: 'Animal',
  snake_meat: 'Animal',
  toughat_meat: 'Animal',
  octopus_ink_sac: 'Animal',
  paw: 'Animal',
  pelt: 'Animal',
  skull: 'Animal',
  small_tortoise_shell: 'Animal',
  tail: 'Animal',
  tooth: 'Animal',
  unicorn_twisted_horn: 'Animal',
  wool: 'Animal',
  // Fruits
  apples: 'Fruits',
  cherries: 'Fruits',
  blue_grapes: 'Fruits',
  green_grapes: 'Fruits',
  lemons: 'Fruits',
  olives: 'Fruits',
  oranges: 'Fruits',
  blueberries: 'Fruits',
  lingonberries: 'Fruits',
  raspberries: 'Fruits',
  acorns: 'Fruits',
  chestnuts: 'Fruits',
  hazelnuts: 'Fruits',
  pinenuts: 'Fruits',
  walnuts: 'Fruits',
}

// Lista de todas as categorias disponíveis
export const CATEGORIES = ['Shards', 'Bricks', 'Construction', 'Metals', 'Ores', 'Smithing', 'Wood', 'Farm', 'Garden', 'Animal', 'Fruits']

// Verifica se um tipo de item é um Ore
export const isOre = (itemType) => {
  return ITEM_CATEGORIES[itemType] === 'Ores'
}

// Verifica se um tipo de item é um Log de madeira
export const isLog = (itemType) => {
  if (ITEM_CATEGORIES[itemType] !== 'Wood') {
    return false
  }
  return typeof itemType === 'string' && itemType.endsWith('_log')
}

// Verifica se um tipo de item é um Shaft de madeira
export const isShaft = (itemType) => {
  if (ITEM_CATEGORIES[itemType] !== 'Wood') {
    return false
  }
  return typeof itemType === 'string' && itemType.endsWith('_shaft')
}

// Cores para os gráficos (cores específicas para cada tipo)
const colorMap = {
  stone_brick: 'rgba(139, 69, 19, 1)',        // Marrom - Stone Brick
  colossus_brick: 'rgba(105, 105, 105, 1)',  // Cinza escuro - Colossus Brick
  slate_brick: 'rgba(112, 128, 144, 1)',      // Cinza ardósia - Slate Brick
  marble_brick: 'rgba(255, 250, 250, 1)',     // Branco neve - Marble Brick
  sandstone_brick: 'rgba(210, 180, 140, 1)',  // Tan - Sandstone Brick
  pottery_brick: 'rgba(160, 82, 45, 1)',      // Sienna - Pottery Brick
  clay: 'rgba(205, 133, 63, 1)',              // Peru - Clay
  sand: 'rgba(238, 203, 173, 1)',             // Pêssego - Sand
  dirt: 'rgba(101, 67, 33, 1)',               // Marrom escuro - Dirt
  stone_shard: 'rgba(169, 169, 169, 1)',     // Cinza - Stone Shard
  slate_shard: 'rgba(119, 136, 153, 1)',     // Cinza claro - Slate Shard
  marble_shard: 'rgba(220, 220, 220, 1)',    // Cinza claro - Marble Shard
  sandstone_shard: 'rgba(184, 134, 11, 1)',  // Dourado escuro - Sandstone Shard
  mortar: 'rgba(128, 128, 128, 1)',            // Cinza - Mortar
  // Metals
  iron_lump: 'rgba(192, 192, 192, 1)',        // Prata - Iron
  copper_lump: 'rgba(184, 115, 51, 1)',       // Cobre - Copper
  silver_lump: 'rgba(192, 192, 192, 1)',      // Prata brilhante - Silver
  gold_lump: 'rgba(255, 215, 0, 1)',          // Dourado - Gold
  tin_lump: 'rgba(200, 200, 200, 1)',         // Cinza claro - Tin
  zinc_lump: 'rgba(220, 220, 220, 1)',        // Cinza prateado - Zinc
  lead_lump: 'rgba(64, 64, 64, 1)',           // Cinza escuro - Lead
  empyrean_lump: 'rgba(138, 43, 226, 1)',     // Roxo - Empyrean
  steel_lump: 'rgba(128, 128, 128, 1)',        // Cinza aço - Steel
  brass_lump: 'rgba(181, 166, 66, 1)',        // Latão - Brass
  bronze_lump: 'rgba(205, 127, 50, 1)',       // Bronze - Bronze
  electrum_lump: 'rgba(255, 215, 0, 1)',      // Dourado eletro - Electrum
  glimmersteel_lump: 'rgba(176, 196, 222, 1)', // Azul aço - Glimmersteel
  adamantine_lump: 'rgba(75, 0, 130, 1)',     // Índigo escuro - Adamantine
  seryll_lump: 'rgba(255, 20, 147, 1)',       // Rosa choque - Seryll
  // Ores
  iron_ore: 'rgba(139, 69, 19, 1)',           // Marrom ferrugem - Iron Ore
  copper_ore: 'rgba(160, 82, 45, 1)',         // Marrom cobre - Copper Ore
  silver_ore: 'rgba(192, 192, 192, 1)',       // Prata - Silver Ore
  gold_ore: 'rgba(218, 165, 32, 1)',          // Dourado - Gold Ore
  tin_ore: 'rgba(169, 169, 169, 1)',          // Cinza - Tin Ore
  zinc_ore: 'rgba(200, 200, 200, 1)',         // Cinza claro - Zinc Ore
  lead_ore: 'rgba(105, 105, 105, 1)',         // Cinza escuro - Lead Ore
  // Smithing
  small_nail: 'rgba(192, 192, 192, 1)',       // Prata - Small Nail
  large_nail: 'rgba(128, 128, 128, 1)',       // Cinza - Large Nail
  ribbon: 'rgba(255, 20, 147, 1)',             // Rosa - Ribbon
  // Wood - cores baseadas em tons de marrom/bege
  // Cores padrão para madeira (será aplicada a todos os tipos de Wood se não especificada)
}

// Gerar cores dinamicamente para tipos Wood baseado no padrão de nome
const woodColorMap = {
  apple: 'rgba(139, 90, 43, 1)',        // Marrom avermelhado
  birch: 'rgba(245, 245, 220, 1)',      // Bege
  cedar: 'rgba(160, 82, 45, 1)',        // Sienna
  cherry: 'rgba(139, 69, 19, 1)',       // Marrom escuro
  chestnut: 'rgba(152, 84, 67, 1)',     // Marrom castanha
  fir: 'rgba(101, 67, 33, 1)',          // Marrom muito escuro
  lemon: 'rgba(255, 250, 205, 1)',      // Bege claro
  linden: 'rgba(238, 203, 173, 1)',     // Pêssego
  maple: 'rgba(205, 133, 63, 1)',       // Peru
  oak: 'rgba(139, 69, 19, 1)',          // Marrom
  oleander: 'rgba(160, 82, 45, 1)',     // Sienna
  olive: 'rgba(107, 142, 35, 1)',       // Verde oliva
  orange: 'rgba(255, 165, 0, 1)',       // Laranja
  pine: 'rgba(85, 107, 47, 1)',         // Verde escuro oliva
  walnut: 'rgba(92, 51, 23, 1)',        // Marrom noz
  willow: 'rgba(119, 136, 153, 1)',     // Cinza ardósia
  blueberry: 'rgba(75, 0, 130, 1)',     // Índigo
  raspberry: 'rgba(199, 21, 133, 1)',   // Rosa escuro
  grape: 'rgba(138, 43, 226, 1)',       // Roxo
  hazelnut: 'rgba(210, 180, 140, 1)',   // Tan
  thorn: 'rgba(139, 69, 19, 1)',        // Marrom
  lavender: 'rgba(230, 230, 250, 1)',   // Lavanda
  camelia: 'rgba(255, 182, 193, 1)',    // Rosa claro
  rose: 'rgba(255, 20, 147, 1)',        // Rosa choque
  lingoberry: 'rgba(219, 112, 147, 1)', // Rosa pálido
}

// Adicionar cores para todos os tipos Wood
const woodTypes = ['apple', 'birch', 'cedar', 'cherry', 'chestnut', 'fir', 'lemon', 'linden', 'maple', 'oak', 'oleander', 'olive', 'orange', 'pine', 'walnut', 'willow', 'blueberry', 'raspberry', 'grape', 'hazelnut', 'thorn', 'lavender', 'camelia', 'rose', 'lingoberry']
const woodItems = ['log', 'plank', 'wooden_beam', 'shaft', 'branch', 'peg', 'tenon']

woodTypes.forEach(wood => {
  woodItems.forEach(item => {
    const key = `${wood}_${item}`
    const baseColor = woodColorMap[wood] || 'rgba(139, 69, 19, 1)' // Marrom padrão
    colorMap[key] = baseColor
  })
})

export const ITEM_TYPE_COLORS = {}
ITEM_TYPES.forEach((item) => {
  ITEM_TYPE_COLORS[item.value] = colorMap[item.value] || 'rgba(100, 149, 237, 1)'
})

